services:
  db:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: quotation_db
      MARIADB_USER: app
      MARIADB_PASSWORD: app
    ports:
      - "3306:3306"
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --innodb-file-per-table=1
      --innodb-flush-log-at-trx-commit=1
      --innodb-buffer-pool-size=256M
    volumes:
      - mariadbdata:/var/lib/mysql
volumes:
  mariadbdata:
